displayThisText(typeof hw)
displayThisText(typeof true)
displayThisText(typeof 42)
displayThisText(typeof 42n)
displayThisText(typeof Symbol())
displayThisText(typeof null)
displayThisText(typeof $)